# Generated by Django 2.0.5 on 2018-05-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180517_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view', 'Can view employees')]},
        ),
    ]
