# Generated by Django 2.0.5 on 2018-05-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180519_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_view', 'Can view customers')]},
        ),
    ]
