# Generated by Django 2.0.5 on 2018-05-19 15:03

from django.db import migrations

def create_employees_group(apps, schema_editor):

    Group = apps.get_model('auth','Group')
    Group.objects.get_or_create(name='Employees')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180519_1459'),
    ]

    operations = [
        migrations.RunPython(create_employees_group)
    ]
