# Generated by Django 2.0.5 on 2018-05-19 15:17

from django.db import migrations
from django.contrib.auth.management import create_permissions


def insert_permissions_to_employees_group(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Customer = apps.get_model('users', 'Customer') 
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth','Permission')
    ContentType = apps.get_model("contenttypes", "ContentType")
    
    customer_content_type = ContentType.objects.get_for_model(Customer)
    employees_group, _ = Group.objects.get_or_create(name='Employees')
    permission_can_view = Permission.objects.get(
        name='Can view customers',
        codename='can_view',
        content_type=customer_content_type
    )
    employees_group.permissions.add(permission_can_view)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180519_1503'),
    ]

    operations = [
        migrations.RunPython(insert_permissions_to_employees_group)
    ]
